### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Crypt0nit** [jikamens/keyless-entry#2]
Hi,

after executing the script on a Debian system I get the following message:

root@proxmox:/usr/local/bin# ./keyless-entry.sh configure
Traceback (most recent call last):
  File "/usr/local/bin/./keyless-entry.sh", line 392, in <module>
    main()
  File "/usr/local/bin/./keyless-entry.sh", line 388, in main
    args.func(args)
  File "/usr/local/bin/./keyless-entry.sh", line 244, in configure
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cryptsetup'

What can I do?

Greetings

**Comment by jikamens** [comment]
Install cryptsetup. I've updated [README.md](../#installation) to reflect this.
