### ISSUE TITLE
Does not work with ZFS

### ISSUE THREAD

**Issue by VSCBSt** [jikamens/keyless-entry#3]
```
sudo /usr/local/bin/keyless-entry configure
Traceback (most recent call last):
  File "/usr/local/bin/keyless-entry", line 409, in <module>
    main()
  File "/usr/local/bin/keyless-entry", line 405, in main
    args.func(args)
  File "/usr/local/bin/keyless-entry", line 235, in configure
    filesystems, keyless_content = make_keyless_content(crypttab_file)
  File "/usr/local/bin/keyless-entry", line 152, in make_keyless_content
    boot_mountpoint = get_boot_mountpoint()
  File "/usr/local/bin/keyless-entry", line 146, in get_boot_mountpoint
    raise Exception(f'Could not find by-uuid device for {real_device}')
Exception: Could not find by-uuid device for ubuntu_4k16es

```

**Comment by jikamens** [comment]
Hmm. Can you send me the output of the following commands run as root?
```
find /dev/disk/by-uuid -ls
findmnt -J /boot
```
Thanks.

**Comment by VSCBSt** [comment]
$ find /dev/disk/by-uuid -ls
      379      0 drwxr-xr-x   2 root     root          160 Feb 22 09:29 /dev/disk/by-uuid
      949      0 lrwxrwxrwx   1 root     root           10 Feb 22 09:29 /dev/disk/by-uuid/9390################################ -> ../../dm-1
      914      0 lrwxrwxrwx   1 root     root           15 Feb 22 09:29 /dev/disk/by-uuid/0695-#### -> ../../nvme0n1p1
      903      0 lrwxrwxrwx   1 root     root           10 Feb 22 09:29 /dev/disk/by-uuid/924d################################ -> ../../dm-0
      781      0 lrwxrwxrwx   1 root     root            9 Feb 22 09:29 /dev/disk/by-uuid/ed72################################ -> ../../zd0
      711      0 lrwxrwxrwx   1 root     root           15 Feb 22 09:29 /dev/disk/by-uuid/6253############### -> ../../nvme0n1p4
      699      0 lrwxrwxrwx   1 root     root           15 Feb 22 09:29 /dev/disk/by-uuid/4321############### -> ../../nvme0n1p3
$ findmnt -J /boot
{
   "filesystems": [
      {
         "target": "/boot",
         "source": "bpool/BOOT/ubuntu_4k16es",
         "fstype": "zfs",
         "options": "rw,nodev,relatime,xattr,posixacl"
      }
   ]
}

**Comment by jikamens** [comment]
Ah. I don't know how to make this work with ZFS because I don't use it. :-(
